eco-shop_cart/cart_app/urls.py
from django.urls import path
from . import views

app_name='cart_app'


urlpatterns = [
    
    path('add/<int:pr_id>/',views.add_cart,name='addcart'),
    path('cart',views.cart_details,name='cartdetails'),
    path('remove/<int:pro_id>/',views.cart_remove,name='cart_remove'),
    path('delete/<int:pr_id>/',views.deletion,name='cart_delete'),

]

eco-shop_cart/ecoshop_app/urls.py
from django.urls import path
from . import views

app_name='ecoshop_app'


urlpatterns = [
    path('',views.allproductcat,name='allproductcat'),
    path('<slug:c_slug>/',views.allproductcat,name='product_by_cat'),
    path('<slug:c_slug>/<slug:p_slug>',views.product,name='product_view')
]

eco-shop_cart/ecoshop_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from ecoshop_project import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('ecoshop_app.urls')),
    path('search/',include('search_app.urls')),
    path('cart/', include('cart_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eco-shop_cart/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'


urlpatterns = [
    path('search',views.search_view,name='searchview'),

]

eco-shop_cart/cart_app/models.py
from django.db import models

from ecoshop_app.models import Product


# Create your models here.

class Cart(models.Model):
    cartId = models.CharField(max_length=250,blank=True)
    date_added = models.DateTimeField(auto_now_add =True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']
    def __str__(self):
        return '{}'.format(self.cartId)
class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return '{}'.format(self.product)

eco-shop_cart/ecoshop_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='category')

    def get_url(self):
        return reverse('ecoshop_app:product_by_cat',args=[self.slug])
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name
class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    img = models.ImageField(upload_to='product')
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    def get_url(self):
        return reverse('ecoshop_app:product_view',args=[self.category.slug,self.slug])
    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
    def __str__(self):
        return '{}'.format(self.name)

eco-shop_cart/search_app/models.py
from django.db import models

# Create your models here.

eco-shop_cart/cart_app/views.py
from django.shortcuts import render, redirect, get_object_or_404

from cart_app.models import Cart, CartItem
from ecoshop_app.models import Product
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart
def add_cart(request,pr_id):
    product = Product.objects.get(id=pr_id)
    try:
        cart = Cart.objects.get(cartId=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cartId = _cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()


    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            cart = cart,
            quantity = 1

        )
        cart_item.save()
    return redirect('cart_app:cartdetails')

def cart_details(request,total=0,counter=0,cart_item=None):
    try:
        cart = Cart.objects.get(cartId = _cart_id(request))

        cart_items = CartItem.objects.filter(cart=cart,active=True)
        print(cart_items)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter,))

def cart_remove(request,pro_id):
    cart = Cart.objects.get(cartId=_cart_id(request))
    product = get_object_or_404(Product,id=pro_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart_app:cartdetails')

def deletion(request,pr_id):
    cart = Cart.objects.get(cartId=_cart_id(request))
    product = get_object_or_404(Product, id=pr_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart_app:cartdetails')

eco-shop_cart/ecoshop_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator,InvalidPage,EmptyPage
from .models import Category, Product


# Create your views here.

# def index(request):
#     return HttpResponse('hello my app')


def allproductcat(request,c_slug=None):
    c_page = None
    products_list = None

    if c_slug !=None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    pagenator = Paginator(products_list,6)
    try:
        page= int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products = pagenator.page(page)
    except(InvalidPage,EmptyPage):
        products = pagenator.page(pagenator.num_pages)



    return render(request,'category.html',{'category':c_page,'products':products})


def product(request,c_slug,p_slug):
    try:
        products = Product.objects.get(category__slug=c_slug,slug=p_slug)
    except Exception as e:
        print("error")
        raise e
    return render(request,'product.html',{'products':products})

eco-shop_cart/search_app/views.py
from django.db.models import Q
from django.shortcuts import render

from ecoshop_app.models import Product


# Create your views here.

def search_view(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

eco-shop_cart/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block metadescription %}{% endblock %}
    <link href="https://fonts.googleapis.com/css2?family=Mooli&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/1a29708ef5.js" crossorigin="anonymous"></script>
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link href="{% static '/css/style.css' %}" rel="stylesheet" >

    <title>{% block title %}{% endblock%}</title>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
   <div class="container"> {% block content %}{% endblock %}</div>
</div>
{% include 'footer.html' %}
<script src="{% static '/js/popper.min.js' %}"></script>
<script src="{% static '/js/bootstrap.min.js' %}" ></script>
</body>
</html>

eco-shop_cart/templates/cart.html
{% extends 'base.html' %}
{% load static %}


{% block metadescription %}

<meta name="description" content="{{products.desc | truncatewords:155}}">


{% endblock %}

{% block title %}

{{products.name}} -mocajo online shop

{% endblock %}
{% block content %}

{% if not cart_items %}

<div class="text-center">
<br>
<h1 class="text-center my_title" >Your shopping cart is empty</h1>
<br>
<p class="text-center">Please Click <a class="btn btn-success" href="{% url 'ecoshop_app:allproductcat'%}">Here</a></p> to continue shopping

</div>

{% else %}

<div class="text-center">
<br>
<h1 class="text-center">Your shopping cart</h1>
<br>
</div>
<div class="row mx-auto">
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
<table class="table my_table">
<thead class="my_thead">
    <tr>
        <th colspan="5">
            Cart Items
        </th>
    </tr>
</thead>
<tbody>
    
    {% for cart_item in cart_items  %}
        <tr>
            <td>
                <a href="{{cart_item.product.get_url}}"><img style="width:100px; height:100px;" src="{{cart_item.product.img.url}}" alt="" class="float-left rounded"></a>
            </td>
            <td class="text-left">
                {{cart_item.product.name}}
                <br>
               SKU: {{cart_item.product.id}}
               <br>
               Price: ${{cart_item.product.price}}
               <br>
               Quantity: {{cart_item.quantity}} X ${{cart_item.product.price}}


            </td>
            <td>
                ${{cart_item.sub_total}}
            </td>
            
            {% if cart_item.quantity < cart_item.product.stock %}
                <td><a href="{% url 'cart_app:addcart' cart_item.product.id %}" class="custom_a "><li class="custom_icon fa fa-plus"></li></a>
              <br><a href="{% url 'cart_app:cart_remove' cart_item.product.id %} "><li class="fa fa-minus custom_icon"></li></a>
                    <br>
                    <a href="{% url 'cart_app:cart_delete' cart_item.product.id %}"><li class="fa fa-trash custom_icon"></li></a>
                </td>
            {% endif %}

                


        </tr>
    {% endfor %}
        
</tbody>
</table>

</div>

    <div class="col-12 col-sm-12 col-md-6 col-lg-6 text-center" >
    <table class="table my_table" >
    <thead class="my_thead">
        <tr>
            <th>
                Check Out
            </th>
        </tr>
    </thead>
    <tbody>
<tr>
    <td>
        Please Review your shopping Cart items Before proceeding with the order payment
    </td>
</tr>

    </tbody>
</table>
<div class="mx-auto">
<a href="{% url 'ecoshop_app:allproductcat' %}" class="btn btn-secondary btn-block my_button">Continue shopping</a>

</div>
    </div>
</div>


{% endif %}
{% endblock %}

eco-shop_cart/templates/category.html
{% extends 'base.html' %}
{% load static %}


{% block metadescription %}
{% if category %}
<meta name="description" content="{{category.desc | truncatewords:155}}">

{% else %}
<meta name="description" content="mocajo makes you greate shopping feel">

{% endif %}
{% endblock %}

{% block title %}
{% if category %}
{{category.name}} -mocajo online shop
{% else %}
see our New collection -mocajo online shop
{% endif %}
{% endblock %}

{% block content %}
{% if category %}
<div>
<div class="row my_row_class">
    <div class="mx-auto">
    <h4><a  href="{% url 'ecoshop_app:allproductcat' %}">Our all products</a> </h4>
</div>
    </div>
    </div>
{% endif %}
{% if category %}
<div class="mx-auto">
    <img class="my_img" src="{{category.img.url}}" alt="{{category.name}}">

</div>
<div>
    <h3 class="text-center my_title">{{category.name}}</h3>
    <p class="text-justify">{{category.desc}}</p>
</div>

{% else %}
<div>
    <img class="my_img my_img_pad" src="{% static 'img/banner.png' %}" alt="{{category.name}}">

</div>
<div>
    <h3 class="text-center my_title">Our all products</h3>
    <p class="text-justify">opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
</p>
</div>

{% endif %}

<div class="container">
    <div class="row mx-auto">
        {% for pr in products.object_list %}
        <div class=" my_margin col-9 col-sm-12 col-md-4 " >
            <div class="card text-center " style="min-width:18rem;">

                    <div>
                <a href="{{pr.get_url}}"><img class="pr_img card-img-top" src="{{pr.img.url}}" alt="{{pr.name}}"></a>
            </div>
            <div class="card-body">
                <h3>{{pr.name}}</h3>
                <p><b>{{pr.price}}</b></p>
                <p>{{pr.desc}}</p>
            </div>
                </div>

        </div>
      {% endfor %}
    </div>
<div class="mx-auto">
{% if products.paginator.num_pages > 1 %}

    <hr>

    <div class="text-center" style="padding-bottom:20px;">
{% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm">{{pg}}</a>
{% endfor %}

    </div>

    {% endif %}
</div>
</div>
{% endblock %}

eco-shop_cart/templates/footer.html
<footer class="">
<div class="my_footer">
<p class="text-center" >&copy;Mocajo Pvt Limited 2023 .All Rights Reserved</p>
    </div>
    </footer>

eco-shop_cart/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ecoshop_app:allproductcat'%}"><img src="{% static 'img/logoimag.png' %}" alt="logoimage" style="width:250px; height:80px"></a>
    </center>

</header>

eco-shop_cart/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'ecoshop_app:allproductcat'%}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Shop</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'ecoshop_app:allproductcat' %}">All products</a></li>
              <hr>

              {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
 {% endfor %}
          </ul>
        </li>
          {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link  " href="{% url 'cart_app:cartdetails' %}" style="font-size:20px; color:red;" ><i class="fa-solid fa-cart-shopping "></i>({{item_count}})</a>
        </li>
          {% endif %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'search_app:searchview' %}" method="get">
          {% csrf_token %}
        <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success " type="submit"><i class="fa-solid fa-magnifying-glass" ></i></button>
      </form>
    </div>
  </div>
</nav>

eco-shop_cart/templates/product.html
{% extends 'base.html' %}
{% load static %}


{% block metadescription %}

<meta name="description" content="{{products.desc | truncatewords:155}}">


{% endblock %}

{% block title %}

{{products.name}} -mocajo online shop

{% endblock %}
{% block content %}
<div class="row my_pr_row">
    <div class="mx-auto">
        <p><a href="{% url 'ecoshop_app:allproductcat' %}">Home</a> | <a href="{{products.category.get_url}}">{{products.category}}</a> | {{products.name}} </p>
    </div>
</div>
<div class="container">
<br>
<div  class="row ">
    <div class="col-12 col-md-12 col-sm-12 col-lg-6 text-center">
        <div style="min-width:18rem; pr_p_img">
            <img style="width:400px; height:460px;" src="{{products.img.url}}" alt="{{products.name}}">
        </div>
    </div>



    <div class="col-12 col-md-12 col-sm-12 col-lg-6 ">
        <div>
        <h3 class="my_prod_title">{{products.name}}</h3>
        <p>{{products.price}}</p>
        <h3 class="my_title">Product Description</h3>
        <p class="text-justify my_prod_text">{{products.desc}}</p>
        {% if products.stock <= 0 %}
        <p class="text-justify my_prod_text"><b>Out of stock</b></p>
        {% else %}
        <a class=" btn btn-secondary" href="{% url 'cart_app:addcart' products.id %}">Add to cart</a>
        {% endif %}
        </div>
    </div>


    </div>
    </div>
{% endblock %}

eco-shop_cart/templates/search.html
{% extends 'base.html' %}
{% load static %}


{% block metadescription %}

<meta name="description" content="{{products.desc | truncatewords:155}}">


{% endblock %}

{% block title %}

{{products.name}} -mocajo online shop

{% endblock %}

{% block content %}
<div>
    <p>you have Searched For: {{query}}</p>

</div>
 <div class="row mx-auto">
        {% for pr in products %}
        <div class=" my_margin col-9 col-sm-12 col-md-4 " >
            <div class="card text-center " style="min-width:18rem;">

                    <div>
                <a href="{{pr.get_url}}"><img class="pr_img card-img-top" src="{{pr.img.url}}" alt="{{pr.name}}"></a>
            </div>
            <div class="card-body">
                <h3>{{pr.name}}</h3>
                <p><b>{{pr.price}}</b></p>
                <p>{{pr.desc}}</p>
            </div>
                </div>

        </div>
      {% endfor %}
    </div>


{% endblock %}